version: 2.1
parameters:
  commit-hash:
    type: string
    default: "master"
  integration:
    type: string
    default: "CI"
  blocks:
    type: string
    default: "50"
  genesis:
    type: string
    default: "no"

executors:
  packer:
    docker:
      - image: tendermintdev/docker-hashicorp-go:latest
    environment:
      GAIA_COMMIT_HASH: << pipeline.parameters.commit-hash >>
      INTEGRATION: << pipeline.parameters.integration >>
      AWS_REGION: us-east-1

commands:
  build-docker:
    steps:
      - run:
          name: "Build docker image"
          command: |
            cd ${CIRCLE_BRANCH}
            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
            docker build -t tendermintdev/${CIRCLE_BRANCH} .
            docker push tendermintdev/${CIRCLE_BRANCH}

jobs:
  ami-gaia-sim:
    executor: packer
    steps:
      - checkout
      - run:
          name: "Build execmgmt tool"
          command: |
            git clone https://github.com/cosmos/tools.git
            git checkout ${RUNSIM_COMMIT_HASH}
            cd tools/cmd/execmgmt || exit 1
            go install
      - run:
          name: "Build image and run sim"
          command: |
            if [[ "${INTEGRATION}" == "slack" ]]; then
              export BLOCKS=<< pipeline.parameters.blocks >>
              export GENESIS=<< pipeline.parameters.genesis >>
            fi

            execmgmt -Notify
            cd ami-gaia-sim || exit 1
            packer validate gaiad.json
            packer build gaiad.json

            if [[ "${GENESIS}" == "true" ]]; then
              execmgmt -Genesis
            else
              execmgmt
            fi

  docker-hashicorp-go:
    machine: true
    steps:
      - checkout
      - build-docker

  docker-tendermint-build:
    machine: true
    steps:
      - checkout
      - build-docker

  docker-build-proto:
    machine: true
    steps:
      - checkout
      - build-docker

  iam-management:
    machine: true
    steps:
      - checkout
      - build-docker

  website-deployment-yarn:
    machine: true
    steps:
      - checkout
      - build-docker

  terragrunt:
    machine: true
    steps:
      - checkout
      - build-docker

  docs-deployment:
    machine: true
    steps:
      - checkout
      - build-docker

  docker-protoc:
    machine: true
    steps:
      - checkout
      - build-docker

  docker-tm-db-testing:
    machine: true
    steps:
      - checkout
      - build-docker

workflows:
  version: 2
  build-image:
    jobs:
      - iam-management:
          filters:
            branches:
              only: docker-iam-management

      - website-deployment-yarn:
          filters:
            branches:
              only: docker-website-deployment

      - terragrunt:
          filters:
            branches:
              only: docker-terragrunt

      - docs-deployment:
          filters:
            branches:
              only: docker-docs-deployment

      - docker-hashicorp-go:
          filters:
            branches:
              only: docker-hashicorp-go

      - docker-tendermint-build:
          filters:
            branches:
              only: docker-tendermint-build

      - docker-protoc:
          filters:
            branches:
              only: docker-protoc

      - docker-build-proto:
          filters:
            branches:
              only: docker-build-proto

      - docker-tm-db-testing:
          filters:
            branches:
              only: docker-tm-db-testing

  run-gaia-sim:
    jobs:
      - ami-gaia-sim:
          context: gaia-sim-dev
          filters:
            branches:
              only: master

      - ami-gaia-sim:
          context: gaia-sim-prod
          filters:
            branches:
              only: ami-gaia-sim
