version: 2.1

commands:
  build_docker_image:
    parameters:
      step_name:
        type: string
      image_name:
        type: string
      organization:
        type: string
    steps:
      - run:
          name: << parameters.step_name >>
          command: |
            cd << parameters.image_name >>
            docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
            docker build -t << parameters.organization >>/<< parameters.image_name >> .
            docker push << parameters.organization >>/<< parameters.image_name >>

jobs:
  gaiad-validator-ecs:
    machine: true
    steps:
      - checkout
      - build_docker_image:
          step_name: "Build image: gaiad ECS validator"
          image_name: "gaiad_validator_ecs"
          organization: "testnets"

  gaiacli-ecs:
    machine: true
    steps:
      - checkout
      - build_docker_image:
          step_name: "Build image: gaiacli ECS"
          image_name: "gaiacli_ecs"
          organization: "testnets"

  iam-management:
    machine: true
    steps:
      - checkout
      - build_docker_image:
          step_name: "Build image: IAM management"
          image_name: "iam_management"
          organization: "tendermintdev"

  website-deployment-yarn:
    machine: true
    steps:
      - checkout
      - build_docker_image:
          step_name: "Build image: website deployment"
          image_name: "website_deployment"
          organization: "tendermintdev"

  voyager-node-browser:
    machine: true
    steps:
      - checkout
      - build_docker_image:
          step_name: "Build image: voyager node-browsers"
          image_name: "voyager_node_browser"
          organization: "tendermintdev"

  voyager-node:
    machine: true
    steps:
      - checkout
      - build_docker_image:
          step_name: "Build image: voyager node"
          image_name: "voyager_node"
          organization: "tendermintdev"

  terragrunt:
    machine: true
    steps:
      - checkout
      - build_docker_image:
          step_name: "Build image: terragrunt"
          image_name: "terragrunt"
          organization: "tendermintdev"

  docs-deployment:
    machine: true
    steps:
      - checkout
      - build_docker_image:
          step_name: "Build image: jq_curl"
          image_name: "jq_curl"
          organization: "tendermintdev"

workflows:
  version: 2.1
  build-image:
    jobs:
      - gaiad-validator-ecs:
          filters:
            branches:
              only: docker-gaiad-validator-ecs

      - gaiacli-ecs:
          filters:
            branches:
              only: docker-gaiacli-ecs

      - iam-management:
          filters:
            branches:
              only: docker-iam-management

      - website-deployment-yarn:
          filters:
            branches:
              only: docker-website-deployment-yarn

      - docs-deployment:
          filters:
            branches:
              only: docker-docs-deployment

      - voyager-node-browser:
          filters:
            branches:
              only: docker-voyager-node-browser

      - voyager-node:
          filters:
            branches:
              only: docker-voyager-node

      - terragrunt:
          filters:
            branches:
              only: docker-terragrunt

      - docs-deployment:
          filters:
            branches:
              only: docker-docs-deployment
